version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    depends_on:
      - mongodb
    environment:
      - PORT=8080
      - NODE_ENV=production
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=thm
      - DB_MONGO_USERNAME=some_username
      - DB_MONGO_PASSWORD=veryStrongPassword1

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=thm
      - MONGO_INITDB_ROOT_USERNAME=some_username
      - MONGO_INITDB_ROOT_PASSWORD=veryStrongPassword1

volumes:
  mongodb-data:
